services:
  bitcoind:
    build:
      context: .
      dockerfile: bitcoin-knots/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    container_name: bitcoind
    restart: unless-stopped
    volumes:
      - ${BITCOIN_DATA_PATH}:/home/bitcoin/.bitcoin
    ports:
      - "8333:8333" # P2P
      - "8332:8332" # RPC
      - "28332:28332" # ZMQ rawblock
      - "28333:28333" # ZMQ rawtx

  fulcrum:
    build:
      context: .
      dockerfile: fulcrum/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    container_name: fulcrum
    restart: unless-stopped
    user: "${USER_ID}:${GROUP_ID}" # Match bitcoin-knots user for .cookie read access
    volumes:
      - ${BITCOIN_DATA_PATH}:/home/bitcoin/.bitcoin:ro # Read-only for .cookie
      - ${FULCRUM_DATA_PATH}:/home/fulcrum/db
    ports:
      - "50001:50001" # Electrum TCP port
    depends_on:
      - bitcoind

  # tor:
  #   profiles:
  #     - tor
  #   build:
  #     context: .
  #     dockerfile: tor/Dockerfile
  #   container_name: tor
  #   restart: unless-stopped
  #   volumes:
  #     - ${TOR_DATA_PATH}:/var/lib/tor/hidden_service
  #   depends_on:
  #     - fulcrum
